spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/PaymentServiceDB
    username: postgres
    password: database
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname:localhost
